name: language_helper_generator
description: A generator for language_helper helps you create a base structure for language_helper.
version: 0.7.6
homepage: https://github.com/lamnhan066/language_helper_generator

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^9.0.0
  args: ^2.7.0
  path: ^1.9.1
  lite_logger: ^0.2.0

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0
  coverage: ^1.15.0
