name: language_helper_generator
description: A generator for language_helper helps you create a base structure for language_helper.
version: 0.7.5
homepage: https://github.com/lamnhan066/language_helper_generator

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^8.4.1
  args: ^2.4.2
  path: ^1.9.1
  lite_logger: ^0.2.0

dev_dependencies:
  test: ^1.25.5
  lints: ^6.0.0
  coverage: ^1.15.0
